---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hello-world
  namespace: hello-world
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - hello.hogwarts.zone
  rules:
    - backendRefs:
        - name: hello-world
          port: 80
