---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:epP8RqTMHYrZ1v37SDEnAdoa+SA46z8dDXXhWUXWRukjZ2I0LN/smg==,iv:815Wb7+x1bzZJjMQnVd2+EvjTL1qSiZUDrmKTs2D350=,tag:An3x2pV36YsH43SN0n4MIA==,type:str]
sops:
  age:
    - recipient: age1v6ewuuyxlt7uug0jfnfwcyz7tarh07ygsyyd6q8ade2st5qhk4eqvt66vd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ2RVcGtMaFlpaFR4T0Zo
        VU5raVVidVlKaVpSVFErMk1ZMnNBV2JveFJBCmQyN0htZHM1dmUyL3d0TVAvRVM0
        WTVJMFFaSEI3eDludU1xYndDVm1tajgKLS0tIEVhb2hyUEVleDVhUllWYXFvRGc3
        T1FKMmMzZW5ZWTdFRDRrOVBqSlp6cEUKE7oU+WxNuGu3FL94FOhgdWN5A9YRICNG
        8ALVEfuRYnO/4Pj+r6Gn2jbdbSgAVge41CrNk6CaCayLFIhENofd9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2025-11-29T16:41:54Z'
  mac: ENC[AES256_GCM,data:LjbLbCclGx21HJVeOMRpAiUilI7bfCZ0M+RHERN7OmCJqaYVCeoXcz3yh9LM4Yf6PwMAWAAN9BjOrc8kMEtNM/u/EAPspvKLQTeAFyfDxaZ30OhYOAp6W0tRpRRL9mGUJ4cM2VGJhlnRTuoru3aUtn6Q2UNjoGn+GPnPyOqYBjI=,iv:TJ1PbaDtRbZvot6vuCqVSs3O5V/TO+F3cxsxUXP+ojo=,tag:/iS+U+Vpgl+nSZ8jzcQGBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
