---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterissuer
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  path: ./infrastructure/talos/clusterissuer
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager
