---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: portainer-agent
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  path: ./infrastructure/talos/portainer-agent
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: metallb
