---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01-cloudflare
  namespace: cert-manager
spec:
  acme:
    email: sebastian.danielsson@proton.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns01-cloudflare
    solvers:
      - dns01:
          cloudflare:
            email: sebastian.danielsson@proton.me
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
